### ISSUE TITLE
Failing to install dependencies

### ISSUE THREAD

**Issue by laygir** [hyperledger/aries-framework-javascript#1401]
Hello 👋

I am quite new to Hyperledger and trying to get familiarity by looking/reading around the repositories of Indy and Aries.

When trying to install dependencies I am getting the following issues and unable to proceed further.
Please let me know what am I doing wrong.

Highlight: Although this appears to be an optional package, I think this is was causing the issue..
```bash
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.15.0/node-v108-darwin-arm64.tar.gz 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.15.0/node-v108-darwin-arm64.tar.gz

```

Full log 👇
```bash
➜  aries-framework-javascript git:(main) yarn install                                               
yarn install v1.22.19
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > @aries-framework/react-native@0.3.3" has unmet peer dependency "react-native-fs@^2.18.0".
warning " > @aries-framework/react-native@0.3.3" has unmet peer dependency "react-native-get-random-values@^1.7.0".
warning "workspace-aggregator-37637622-899d-43db-b5d4-e0725581d9c2 > @aries-framework/react-native > react-native > metro-react-native-babel-transformer@0.64.0" has unmet peer dependency "@babel/core@*".
warning "workspace-aggregator-37637622-899d-43db-b5d4-e0725581d9c2 > @aries-framework/core > @digitalcredentials/jsonld-signatures > isomorphic-webcrypto > expo-random@13.1.1" has unmet peer dependency "expo@*".
warning "workspace-aggregator-37637622-899d-43db-b5d4-e0725581d9c2 > @aries-framework/core > @digitalcredentials/jsonld-signatures > isomorphic-webcrypto > react-native-securerandom@0.1.1" has unmet peer dependency "react-native@*".
warning "workspace-aggregator-37637622-899d-43db-b5d4-e0725581d9c2 > @aries-framework/react-native > react-native > react-native-codegen > jscodeshift@0.11.0" has unmet peer dependency "@babel/preset-env@^7.1.6".
[5/5] 🔨  Building fresh packages...
[1/9] ⠂ indy-sdk
[2/9] ⠂ ref-napi
[-/9] ⠂ waiting...
[4/9] ⠂ @mattrglobal/node-bbs-signatures
warning Error running install script for optional dependency: "/Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/@mattrglobal/node-bbs-signatures: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build=false
Arguments: 
Directory: /Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/@mattrglobal/node-bbs-signatures
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.9
node-pre-gyp info using node@18.15.0 | darwin | arm64
node-pre-gyp info check checked for \"/Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/@mattrglobal/node-bbs-signatures/native/index.node\" (not found)
node-pre-gyp http GET https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.15.0/node-v108-darwin-arm64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.15.0/node-v108-darwin-arm64.tar.gz 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.15.0/node-v108-darwin-arm64.tar.gz
node-pre-gyp ERR! stack     at /Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/@mattrglobal/node-bbs-signatures/node_modules/@mapbox/node-pre-gyp/lib/install.js:67:15
node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
node-pre-gyp ERR! System Darwin 22.3.0
node-pre-gyp ERR! command \"/Users/liger/.nvm/versions/node/v18.15.0/bin/node\" \"/Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/@mattrglobal/node-bbs-signatures/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build=false\"
node-pre-gyp ERR! cwd /Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/@mattrglobal/node-bbs-signatures
node-pre-gyp ERR! node -v v18.15.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.9
node-pre-gyp ERR! not ok 
response status 404 Not Found on https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.15.0/node-v108-darwin-arm64.tar.gz"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "/Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/@mattrglobal/bls12381-key-pair/node_modules/@mattrglobal/node-bbs-signatures: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build=false
Arguments: 
Directory: /Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/@mattrglobal/bls12381-key-pair/node_modules/@mattrglobal/node-bbs-signatures
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.17.0
node-pre-gyp info using node@18.15.0 | darwin | arm64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for \"/Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/@mattrglobal/bls12381-key-pair/node_modules/@mattrglobal/node-bbs-signatures/native/index.node\" (not found)
node-pre-gyp http GET https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.13.0/node-v108-darwin-arm64.tar.gz
node-pre-gyp http 404 https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.13.0/node-v108-darwin-arm64.tar.gz
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.13.0/node-v108-darwin-arm64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/node-pre-gyp/lib/install.js:142:27)
node-pre-gyp ERR! stack     at Request.emit (node:events:525:35)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/request/request.js:1059:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (node:events:513:28)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:701:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (node:_http_client:542:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (node:events:513:28)
node-pre-gyp ERR! stack     at addChunk (node:internal/streams/readable:324:12)
node-pre-gyp ERR! stack     at readableAddChunk (node:internal/streams/readable:297:9)
node-pre-gyp ERR! System Darwin 22.3.0
node-pre-gyp ERR! command \"/Users/liger/.nvm/versions/node/v18.15.0/bin/node\" \"/Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/@mattrglobal/bls12381-key-pair/node_modules/@mattrglobal/node-bbs-signatures/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build=false\"
node-pre-gyp ERR! cwd /Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/@mattrglobal/bls12381-key-pair/node_modules/@mattrglobal/node-bbs-signatures
node-pre-gyp ERR! node -v v18.15.0
[1/9] ⠈ indy-sdk
[2/9] ⠈ ref-napi
[-/9] ⠈ waiting...
[-/9] ⠈ waiting...
error /Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/ref-napi: Command failed.
Exit code: 1
Command: node-gyp-build
Arguments: 
Directory: /Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/ref-napi
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@18.15.0 | darwin | arm64
gyp info find Python using Python version 3.10.9 found at "/opt/homebrew/opt/python@3.10/bin/python3.10"
(node:14842) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /opt/homebrew/opt/python@3.10/bin/python3.10
gyp info spawn args [
gyp info spawn args   '/Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/@npmcli/run-script/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/ref-napi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/@npmcli/run-script/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/liger/Library/Caches/node-gyp/18.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/liger/Library/Caches/node-gyp/18.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/@npmcli/run-script/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/liger/Library/Caches/node-gyp/18.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/ref-napi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
env: python: No such file or directory
make: *** [Release/nothing.a] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/@npmcli/run-script/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 22.3.0
gyp ERR! command "/Users/liger/.nvm/versions/node/v18.15.0/bin/node" "/Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/liger/Sites/sandbox/aries-framework-javascript/node_modules/ref-napi
```

For what it's worth: I am using Macbook M1, I tried in node v16.x.x and node v18.x.x
Also have been trying Indy related repositories, react-native repo and some docker images, unfortunately it's been 2 days and nothing appears to be working for me. 🥺

**Comment by TimoGlastra** [comment]
I think it needs python to be available: `env: python: No such file or directory`

What do you get if you try `python` in your terminal? And if you try `python3`?

https://opensource.com/article/19/5/python-3-default-mac
