### ISSUE TITLE
Node 18 Windows support

### ISSUE THREAD

**Issue by dnaicker86** [hyperledger/aries-framework-javascript#1522]
I added github project combining tutorials from aries docs https://github.com/dnaicker86/aries-js-project-1

When using WSL2 for Windows node 16 and 18 run effectively.

Although when running on Windows directly the following error is shown:
```
npm WARN deprecated @unimodules/core@7.1.2: replaced by the 'expo' package, learn more: https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc
npm WARN deprecated @unimodules/react-native-adapter@6.3.9: replaced by the 'expo' package, learn more: https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\ffi-napi',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\ffi-napi'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\ffi-napi'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\@hyperledger\aries-askar-react-native'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\@hyperledger\\aries-askar-react-native'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\@hyperledger\indy-vdr-nodejs
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --target_arch=$(node scripts/arch.js) --target_platform=$(node scripts/platform.js)
npm ERR! response status 404 Not Found on https://github.com/hyperledger/indy-vdr/releases/download/v0.4.0-dev.16/library-$(node-$(node.tar.gz
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@16.20.1 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\@hyperledger\indy-vdr-nodejs\native\indy_vdr.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/hyperledger/indy-vdr/releases/download/v0.4.0-dev.16/library-$(node-$(node.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/hyperledger/indy-vdr/releases/download/v0.4.0-dev.16/library-$(node-$(node.tar.gz
npm ERR! node-pre-gyp ERR! install error
npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/hyperledger/indy-vdr/releases/download/v0.4.0-dev.16/library-$(node-$(node.tar.gz
npm ERR! node-pre-gyp ERR! stack     at C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\@mapbox\node-pre-gyp\lib\install.js:67:15
npm ERR! node-pre-gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.22621
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--target_arch=$(node" "scripts/arch.js)" "--target_platform=$(node" "scripts/platform.js)"
npm ERR! node-pre-gyp ERR! cwd C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\@hyperledger\indy-vdr-nodejs
npm ERR! node-pre-gyp ERR! node -v v16.20.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\denai\AppData\Local\npm-cache\_logs\2023-07-23T12_56_37_825Z-debug-0.log
```

I am running as administrator to try and alleviate any locks on files when it is trying to remove ffi-napi folder shown in log

I noted these errors in the log is it perhaps indy-sdk instalk related?
```
response status 404 Not Found on https://github.com/hyperledger/indy-vdr/releases/download/v0.4.0-dev.16/library-$(node-$(node.tar.gz
```
```
npm ERR! path C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\@hyperledger\indy-vdr-nodejs
```

**Comment by genaris** [comment]
It looks like it is a problem on the install script on `indy-vdr` (and likely also `anoncreds` and `aries-askar`) which certainly we should fix. But, from your log, I see you are using node 16.20.1, so it does not seem a problem specific to node 18. Is it?

**Comment by dnaicker86** [comment]
> It looks like it is a problem on the install script on `indy-vdr` (and likely also `anoncreds` and `aries-askar`) which certainly we should fix. But, from your log, I see you are using node 16.20.1, so it does not seem a problem specific to node 18. Is it?

@genaris apologies, thank you for spotting that, I tried to run with node 18.16.1 and the following errors display:

```
PS C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1> npm install
npm WARN deprecated @unimodules/core@7.1.2: replaced by the 'expo' package, learn more: https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc
npm WARN deprecated @unimodules/react-native-adapter@6.3.9: replaced by the 'expo' package, learn more: https://blog.expo.dev/whats-new-in-expo-modules-infrastructure-7a7cdda81ebc
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\ffi-napi',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\ffi-napi'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\ffi-napi'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\@hyperledger\\aries-askar-nodejs',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\@hyperledger\aries-askar-nodejs'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\@hyperledger\\aries-askar-nodejs'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\@hyperledger\\aries-askar-react-native',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\@hyperledger\aries-askar-react-native'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\@hyperledger\\aries-askar-react-native'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\@hyperledger',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\@hyperledger\aries-askar-nodejs'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\@hyperledger\\aries-askar-nodejs'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\ffi-napi'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\ffi-napi'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\@cheqd\\sdk\\node_modules\\@cosmjs\\tendermint-rpc',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\@cheqd\sdk\node_modules\@cosmjs\tendermint-rpc'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\@cheqd\\sdk\\node_modules\\@cosmjs\\tendermint-rpc'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\react-native-securerandom',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\react-native-securerandom\android\build\intermediates\classes\debug\com\facebook\imagepipeline'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\react-native-securerandom\\android\\build\\intermediates\\classes\\debug\\com\\facebook\\imagepipeline'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\@hyperledger\anoncreds-nodejsnpm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-pre-gyp install --target_arch=$(node scripts/arch.js) --target_platform=$(node scripts/platform.js)
npm ERR! response status 404 Not Found on https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0/library-$(node-$(node.tar.gz
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@18.16.1 | win32 | x64
npm ERR! node-pre-gyp info check checked for "C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\@hyperledger\anoncreds-nodejs\native\anoncreds.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0/library-$(node-$(node.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0/library-$(node-$(node.tar.gz
npm ERR! node-pre-gyp ERR! install error
npm ERR! node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0/library-$(node-$(node.tar.gz
npm ERR! node-pre-gyp ERR! stack     at C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\@mapbox\node-pre-gyp\lib\install.js:67:15
npm ERR! node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR! node-pre-gyp ERR! System Windows_NT 10.0.22621
npm ERR! node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\denai\\Github\\Hyperledger_Aries\\Test\\aries-js-project-1\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--target_arch=$(node" "scripts/arch.js)" "--target_platform=$(node" "scripts/platform.js)"
npm ERR! node-pre-gyp ERR! cwd C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\@hyperledger\anoncreds-nodejs
npm ERR! node-pre-gyp ERR! node -v v18.16.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\Users\denai\AppData\Local\npm-cache\_logs\2023-07-23T15_51_10_104Z-debug-0.log
```

I noted the following from the log which is :
```
ERR! install response status 404 Not Found on https://github.com/hyperledger/anoncreds-rs/releases/download/v0.1.0/library-$(node-$(node.tar.gz
```

```
check checked for "C:\Users\denai\Github\Hyperledger_Aries\Test\aries-js-project-1\node_modules\@hyperledger\anoncreds-nodejs\native\anoncreds.node" (not found)
```

**Comment by genaris** [comment]
Allright, so the issue is not a matter of `node` version but shell used when running `npm`. Under Windows, it uses `cmd.exe` by default, and currently in `@hyperledger/aries-askar`, `@hyperledger/indy-vdr` and `@hyperledger/anoncreds-rs` install scripts we are relying on bash command substitution for platform detection for binary retrieval. So for it to work you must set your shell to a bash-compatible one, like the one embedded in `git`: 

```
npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
```

Then run your `npm install` and it should retrieve the corresponding DLLs and work normally.

More info in https://github.com/hyperledger/anoncreds-rs/issues/204.

**Comment by dnaicker86** [comment]
@genaris Thank you that resolved the error :)

**Comment by TimoGlastra** [comment]
Interesting. We should add this to the docs I think. Or is there a way to make this work with cmd on windows?

**Comment by berendsliedrecht** [comment]
I think we can make it a pure node.js script which does string substitution in there instead of in a shell.
