### ISSUE TITLE
Force did:key resolver to be always present

### ISSUE THREAD

**Issue by genaris** [hyperledger/aries-framework-javascript#1528]
DIDs module allows dynamically registering its registrars and resolvers, forcing `did:peer` to be always supported because it is a critical DID method for AFJ agents to interact.

In the case of `did:key`, it could be useful to force it as well, considering it is widely used to represent keys in most Aries RFCs and sometimes DID resolution using this type of DID method is called. This idea came from an issue reported at Discord by **Simo56** and **Abdur Rahman** where they wanted to connect a Mobile Agent based on Bifold to a "Cloud Agent" based on AFJ. As they were only defining a `CheqdDidResolver` among their DID resolvers array, their cloud agent threw this error:

```
INFO: Received message with type 'https://didcomm.org/didexchange/1.0/request', recipient key z6MkmpMrjrib5rwUBo8ZF9BoGPHNtwkN1pF9ooww3Cbx7GYK and sender key z6MkpwsBvrKgrDLLQF2WxrJ6R7ozwD6T2b3SxwXEVnE8YiXW {
  "@type": "https://didcomm.org/didexchange/1.0/request",
  "@id": "d6e11f33-7bc6-4c33-b44c-7ff1414ab210",
  "label": "My Wallet - 2619",
  "did": "did:peer:1zQmc4ecoLQzg1pfX6US479BvTCnKq35fDNWnEkDa9kvpx5y",
  "~thread": {
    "pthid": "9b33a1b8-7461-4522-9edc-f2a29bf324ff"
  },
  "did_doc~attach": {
    "@id": "8edf7c79-5964-4b73-aee0-cfcc1df6d8f1",
    "mime-type": "application/json",
    "data": {
      "base64": "eyJAY29udGV4dCI6WyJodHRwczovL3czaWQub3JnL2RpZC92MSJdLCJpZCI6ImRpZDpwZWVyOjF6UW1jNGVjb0xRemcxcGZYNlVTNDc5QnZUQ25LcTM1ZkROV25Fa0RhOWt2cHg1eSIsInNlcnZpY2UiOlt7ImlkIjoiI2lubGluZS0wIiwic2VydmljZUVuZHBvaW50IjoiaHR0cHM6Ly9wdWJsaWMubWVkaWF0b3IuaW5kaWNpb3RlY2guaW8iLCJ0eXBlIjoiZGlkLWNvbW11bmljYXRpb24iLCJwcmlvcml0eSI6MCwicmVjaXBpZW50S2V5cyI6WyIjZjlkMTc0YjItZTJiYS00ZjIyLWEwMDgtYjcyNTdmMGRkYmI4Il0sInJvdXRpbmdLZXlzIjpbImRpZDprZXk6ejZNa3Jpb2FkRmFGVmlwdkJVVTR5VnhyaFhMZTN1UVJUdG1SWjdzbWd1emQ1VFBBI3o2TWtyaW9hZEZhRlZpcHZCVVU0eVZ4cmhYTGUzdVFSVHRtUlo3c21ndXpkNVRQQSJdfV0sImF1dGhlbnRpY2F0aW9uIjpbeyJpZCI6IiNmOWQxNzRiMi1lMmJhLTRmMjItYTAwOC1iNzI1N2YwZGRiYjgiLCJ0eXBlIjoiRWQyNTUxOVZlcmlmaWNhdGlvbktleTIwMTgiLCJjb250cm9sbGVyIjoiI2lkIiwicHVibGljS2V5QmFzZTU4IjoiQlZjOUxjNUZXZnFzSGtCcEhITEZhMkcxN2RwYmNobzZHdmNKZldHN2RWazgifV0sImtleUFncmVlbWVudCI6W3siaWQiOiIjMzZjYTQ2YTAtOTJiZS00MDYxLWE0ZmMtOTI1YTQzMGYxMDRkIiwidHlwZSI6IlgyNTUxOUtleUFncmVlbWVudEtleTIwMTkiLCJjb250cm9sbGVyIjoiI2lkIiwicHVibGljS2V5QmFzZTU4IjoiRzJaeHlHMXRURW9WUHQ1dTlSUXJad0FRaTlXc3VldHdSaWVFWURzd3hTNW4ifV19",
      "jws": {
        "protected": "eyJhbGciOiJFZERTQSIsImp3ayI6eyJrdHkiOiJPS1AiLCJjcnYiOiJFZDI1NTE5IiwieCI6Im0tamVmTmRFTjk0NUNDamUyUTRQRlpReldnVFlMZW5qTnkwemdFcjl1VlUifX0",
        "signature": "jFSYPaYNHdbvi7qpd8DNjKecmyBLJxqtwkrC3L3m7dFUXNvw6g2TPdMA_3T1VDSVIOdg2-jyYdJF15acLKbLDA",
        "header": {
          "kid": "did:key:z6MkpwsBvrKgrDLLQF2WxrJ6R7ozwD6T2b3SxwXEVnE8YiXW"
        }
      }
    }
  }
}
ERROR: Unable to retrieve services for connection '87506463-f4cf-4379-aa03-8268625a803a. Unable to resolve did document for did 'did:key:z6MkrioadFaFVipvBUU4yVxrhXLe3uQRTtmRZ7smguzd5TPA#z6MkrioadFaFVipvBUU4yVxrhXLe3uQRTtmRZ7smguzd5TPA': unsupportedDidMethod No did resolver registered for did method key
ERROR: Error processing inbound message: Unable to retrieve services for connection '87506463-f4cf-4379-aa03-8268625a803a {
  "name": "MessageSendingError",
  "message": "Unable to retrieve services for connection '87506463-f4cf-4379-aa03-8268625a803a",
  "stack": "MessageSendingError: Unable to retrieve services for connection '87506463-f4cf-4379-aa03-8268625a803a\n    at MessageSender.sendMessage (core\\src\\agent\\MessageSender.ts:241:13)\n    at Dispatcher.dispatch (core\\src\\agent\\Dispatcher.ts:95:9)\n    at MessageReceiver.receiveEncryptedMessage (core\\src\\agent\\MessageReceiver.ts:168:5)\n    at MessageReceiver.receiveMessage (core\\src\\agent\\MessageReceiver.ts:96:9)\n    at node\\src\\transport\\HttpInboundTransport.ts:55:9",
  "cause": {
    "name": "AriesFrameworkError",
    "message": "Unable to resolve did document for did 'did:key:z6MkrioadFaFVipvBUU4yVxrhXLe3uQRTtmRZ7smguzd5TPA#z6MkrioadFaFVipvBUU4yVxrhXLe3uQRTtmRZ7smguzd5TPA': unsupportedDidMethod No did resolver registered for did method key",
    "stack": "AriesFrameworkError: Unable to resolve did document for did 'did:key:z6MkrioadFaFVipvBUU4yVxrhXLe3uQRTtmRZ7smguzd5TPA#z6MkrioadFaFVipvBUU4yVxrhXLe3uQRTtmRZ7smguzd5TPA': unsupportedDidMethod No did resolver registered for did method key\n    at DidResolverService.resolveDidDocument (core\\src\\modules\\dids\\services\\DidResolverService.ts:66:13)\n    at DidCommDocumentService.resolveServicesFromDid (core\\src\\modules\\didcomm\\services\\DidCommDocumentService.ts:43:38)\n    at MessageSender.retrieveServicesByConnection (core\\src\\agent\\MessageSender.ts:474:25)\n    at MessageSender.sendMessage (core\\src\\agent\\MessageSender.ts:232:38)\n    at Dispatcher.dispatch (core\\src\\agent\\Dispatcher.ts:95:9)\n    at MessageReceiver.receiveEncryptedMessage (core\\src\\agent\\MessageReceiver.ts:168:5)\n    at MessageReceiver.receiveMessage (core\\src\\agent\\MessageReceiver.ts:96:9)\n    at node\\src\\transport\\HttpInboundTransport.ts:55:9"
  },
  "outboundMessageContext": {
    "message": {
      "@type": "https://didcomm.org/didexchange/1.0/response",
      "@id": "e6c33f55-00f7-4c87-9cd4-ea37035ee08e",
      "did": "did:peer:1zQmUCU8vWm6zHxbkXUjfmYF5kYSLvZv24XF7ceyvtkRe5pv",
      "~thread": {
        "thid": "d6e11f33-7bc6-4c33-b44c-7ff1414ab210"
      },
      "did_doc~attach": {
        "@id": "db1c81e8-547f-4cc5-94f7-c42145665759",
        "mime-type": "application/json",
        "data": {
          "base64": "eyJAY29udGV4dCI6WyJodHRwczovL3czaWQub3JnL2RpZC92MSJdLCJpZCI6ImRpZDpwZWVyOjF6UW1VQ1U4dldtNnpIeGJrWFVqZm1ZRjVrWVNMdlp2MjRYRjdjZXl2dGtSZTVwdiIsInNlcnZpY2UiOlt7ImlkIjoiI2lubGluZS0wIiwic2VydmljZUVuZHBvaW50IjoiaHR0cHM6Ly83OGMxLTItMTk4LTc4LTE2OS5uZ3Jvay1mcmVlLmFwcCIsInR5cGUiOiJkaWQtY29tbXVuaWNhdGlvbiIsInByaW9yaXR5IjowLCJyZWNpcGllbnRLZXlzIjpbIiMyNjFlNjY2Zi1iZTEyLTRkNjctOTk3Ni1mZjdkNmMwMzUyNmYiXSwicm91dGluZ0tleXMiOltdfV0sImF1dGhlbnRpY2F0aW9uIjpbeyJpZCI6IiMyNjFlNjY2Zi1iZTEyLTRkNjctOTk3Ni1mZjdkNmMwMzUyNmYiLCJ0eXBlIjoiRWQyNTUxOVZlcmlmaWNhdGlvbktleTIwMTgiLCJjb250cm9sbGVyIjoiI2lkIiwicHVibGljS2V5QmFzZTU4IjoiOE42cDljVTlrS1QxNUpIclphRHhSSGpQNU5VV2J2em83bzMxQ3Zkd0Mza3cifV0sImtleUFncmVlbWVudCI6W3siaWQiOiIjMjdjMzMxYjItZmZlNi00Nzc5LTk4NzUtODhlNjM1YWJmMDg5IiwidHlwZSI6IlgyNTUxOUtleUFncmVlbWVudEtleTIwMTkiLCJjb250cm9sbGVyIjoiI2lkIiwicHVibGljS2V5QmFzZTU4IjoiOUdOUVZuRlVyM0xyMkJGMjNuejRXR0hHZjFaWlhEdVg2N2R3TnJ1eWlua2IifV19",
          "jws": {
            "protected": "eyJhbGciOiJFZERTQSIsImp3ayI6eyJrdHkiOiJPS1AiLCJjcnYiOiJFZDI1NTE5IiwieCI6ImJXbVVBWGR0bXVIejd0aGowZzNsaUUtOVI3UFhsbnBTRkpXM09GcjZTcFEifX0",       
            "signature": "HuLNeSQXn34YFnJxJwhP41-K7sGj5LGi1sNRynm_HLUQtFgSjo5upkLdPgjXM7DhOX-090AxNKvKVlvIP7ThCQ",
            "header": {
              "kid": "did:key:z6MkmpMrjrib5rwUBo8ZF9BoGPHNtwkN1pF9ooww3Cbx7GYK"
            }
          }
        }
      }
    },

```

**Comment by TimoGlastra** [comment]
Agreed! Let's add it
