### ISSUE TITLE
Unable to receiveInvitation.

### ISSUE THREAD

**Issue by sudddy** [hyperledger/aries-framework-javascript#1552]
Hello all,

Do you have any idea why I'm getting this error? I'm following the tutorial given herein - https://aries.js.org/guides/0.4/tutorials/create-a-connection. 

Env: Node.js.

By the way, I'm not using two separate environments - If I do, I'm not receiving any events. 
So, trying out entirely in node.js.

MessageSendingError: Message is undeliverable to connection 9d2d02c3-4350-4c3b-aa83-7e5805f13608 (demo-agent-aish-test)
    at MessageSender.sendMessage (/Users/sudharsansrinivasan/Desktop/interview-prep/test-backend/node_modules/@aries-framework/core/src/agent/MessageSender.ts:340:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ConnectionsApi.acceptOutOfBandInvitation (/Users/sudharsansrinivasan/Desktop/interview-prep/test-backend/node_modules/@aries-framework/core/src/modules/connections/ConnectionsApi.ts:128:5)
    at async OutOfBandApi.acceptInvitation (/Users/sudharsansrinivasan/Desktop/interview-prep/test-backend/node_modules/@aries-framework/core/src/modules/oob/OutOfBandApi.ts:529:28)
    at async OutOfBandApi._receiveInvitation (/Users/sudharsansrinivasan/Desktop/interview-prep/test-backend/node_modules/@aries-framework/core/src/modules/oob/OutOfBandApi.ts:440:14)

**Comment by TimoGlastra** [comment]
Can you enable logging and post the logs here? And an example of your setup?

**Comment by sudddy** [comment]
@TimoGlastra Thanks for replying - It was a lame port error which I figured it out later.
