### ISSUE TITLE
Agent + Postgres CI/CD [Digital Ocean]

### ISSUE THREAD

**Issue by djleonskennedy** [hyperledger/aries-framework-javascript#1614]
Hello Aries Team!

Trying to deploy a mediator based on an [example](https://github.com/animo/animo-mediator) (code unchanged)

got error (full log)

database is working from PGAdmin

```
[2023-10-24 11:11:19]   error: {
[2023-10-24 11:11:19]     stack: 'Error: Backend error\n' +
[2023-10-24 11:11:19]       'Caused by: error returned from database: database "postgres" does not exist\n' +
[2023-10-24 11:11:19]       '    at cb (/www/node_modules/@hyperledger/aries-askar-nodejs/build/NodeJSAriesAskar.js:44:39)\n' +
[2023-10-24 11:11:19]       '    at Object.<anonymous> (/www/node_modules/ffi-napi/lib/callback.js:66:27)',
[2023-10-24 11:11:19]     message: 'Backend error\n' +
[2023-10-24 11:11:19]       'Caused by: error returned from database: database "postgres" does not exist',
[2023-10-24 11:11:19]     code: 1
[2023-10-24 11:11:19]   },
[2023-10-24 11:11:19]   errorMessage: 'Backend error\n' +
[2023-10-24 11:11:19]     'Caused by: error returned from database: database "postgres" does not exist'
[2023-10-24 11:11:19] }
```

full log

```
[2023-10-24 11:11:15] $ node build/index.js
[2023-10-24 11:11:18] ----------------> askarPostgresConfig {
[2023-10-24 11:11:18]   type: 'postgres',
[2023-10-24 11:11:18]   config: {
[2023-10-24 11:11:18]     host: 'incogme-mediator-beta-do-user-***.db.ondigitalocean.com:25060',
[2023-10-24 11:11:18]     connectTimeout: 5000
[2023-10-24 11:11:18]   },
[2023-10-24 11:11:18]   credentials: {
[2023-10-24 11:11:18]     account: 'doadmin',
[2023-10-24 11:11:18]     password: ***,
[2023-10-24 11:11:18]     adminAccount: 'doadmin',
[2023-10-24 11:11:18]     adminPassword: ***
[2023-10-24 11:11:18]   }
[2023-10-24 11:11:18] }
[2023-10-24 11:11:18] ----------------> WALLET_NAME incogme-mediator-beta
[2023-10-24 11:11:18] 2023-10-24 11:11:18.642  INFO  [DIDComm Chat src/agent.ts:85  createAgent] Using postgres storage 
[2023-10-24 11:11:18] {
[2023-10-24 11:11:18]   walletId: 'incogme-mediator-beta',
[2023-10-24 11:11:18]   host: 'incogme-mediator-beta-do-user-13941840-0.c.db.ondigitalocean.com:25060'
[2023-10-24 11:11:18] }
[2023-10-24 11:11:18] 2023-10-24 11:11:18.653  WARN [DIDComm Chat   AskarModule.register] The '@aries-framework/askar' module is experimental and could have unexpected breaking changes. When using this module, make sure to use strict versions for all @aries-framework packages. 
[2023-10-24 11:11:18] 2023-10-24 11:11:18.667  INFO  [DIDComm Chat   undefined.constructor] Creating agent with config 
[2023-10-24 11:11:18] {
[2023-10-24 11:11:18]   agentConfig: {
[2023-10-24 11:11:18]     label: 'Incogme Mediator',
[2023-10-24 11:11:18]     endpoints: [
[2023-10-24 11:11:18]       'http://localhost:3000',
[2023-10-24 11:11:18]       'ws://localhost:3000'
[2023-10-24 11:11:18]     ],
[2023-10-24 11:11:18]     walletConfig: {
[2023-10-24 11:11:18]       id: 'incogme-mediator-beta',
[2023-10-24 11:11:18]       key: '[*****]',
[2023-10-24 11:11:18]       storage: {
[2023-10-24 11:11:18]         type: 'postgres',
[2023-10-24 11:11:18]         config: {
[2023-10-24 11:11:18]           host: 'incogme-mediator-beta-do-user-13941840-0.c.db.ondigitalocean.com:25060',
[2023-10-24 11:11:18]           connectTimeout: 5000
[2023-10-24 11:11:18]         },
[2023-10-24 11:11:18]         credentials: '[*****]'
[2023-10-24 11:11:18]       }
[2023-10-24 11:11:18]     },
[2023-10-24 11:11:18]     useDidSovPrefixWhereAllowed: true,
[2023-10-24 11:11:18]     logger: 2,
[2023-10-24 11:11:18]     autoUpdateStorageOnStartup: true,
[2023-10-24 11:11:18]     didCommMimeType: 'application/ssi-agent-wire',
[2023-10-24 11:11:18]     agentDependencies: true
[2023-10-24 11:11:18]   }
[2023-10-24 11:11:18] }
[2023-10-24 11:11:18] 2023-10-24 11:11:18.683  INFO  [DIDComm Chat   WalletApi.initialize] Initializing wallet 'incogme-mediator-beta' 
[2023-10-24 11:11:18] {
[2023-10-24 11:11:18]   id: 'incogme-mediator-beta',
[2023-10-24 11:11:18]   key: '[*****]',
[2023-10-24 11:11:18]   storage: {
[2023-10-24 11:11:18]     type: 'postgres',
[2023-10-24 11:11:18]     config: {
[2023-10-24 11:11:18]       host: 'incogme-mediator-beta-do-user-13941840-0.c.db.ondigitalocean.com:25060',
[2023-10-24 11:11:18]       connectTimeout: 5000
[2023-10-24 11:11:18]     },
[2023-10-24 11:11:18]     credentials: '[*****]'
[2023-10-24 11:11:18]   }
[2023-10-24 11:11:18] }
[2023-10-24 11:11:18] 2023-10-24 11:11:18.878  DEBUG [DIDComm Chat   AskarWallet._open] Wallet 'incogme-mediator-beta' not found 
[2023-10-24 11:11:18] 2023-10-24 11:11:18.880  DEBUG [DIDComm Chat   AskarWallet.createAndOpen] Creating wallet 'incogme-mediator-beta 
[2023-10-24 11:11:19] 2023-10-24 11:11:19.109  ERROR [DIDComm Chat   AskarWallet.createAndOpen] Error creating wallet 'incogme-mediator-beta' 
[2023-10-24 11:11:19] {
[2023-10-24 11:11:19]   error: {
[2023-10-24 11:11:19]     stack: 'Error: Backend error\n' +
[2023-10-24 11:11:19]       'Caused by: error returned from database: database "postgres" does not exist\n' +
[2023-10-24 11:11:19]       '    at cb (/www/node_modules/@hyperledger/aries-askar-nodejs/build/NodeJSAriesAskar.js:44:39)\n' +
[2023-10-24 11:11:19]       '    at Object.<anonymous> (/www/node_modules/ffi-napi/lib/callback.js:66:27)',
[2023-10-24 11:11:19]     message: 'Backend error\n' +
[2023-10-24 11:11:19]       'Caused by: error returned from database: database "postgres" does not exist',
[2023-10-24 11:11:19]     code: 1
[2023-10-24 11:11:19]   },
[2023-10-24 11:11:19]   errorMessage: 'Backend error\n' +
[2023-10-24 11:11:19]     'Caused by: error returned from database: database "postgres" does not exist'
[2023-10-24 11:11:19] }
[2023-10-24 11:11:19] 
[2023-10-24 11:11:19] /www/node_modules/@aries-framework/askar/build/wallet/AskarWallet.js:118
[2023-10-24 11:11:19]             throw new core_1.WalletError(errorMessage, { cause: error });
[2023-10-24 11:11:19]                   ^
[2023-10-24 11:11:19] WalletError: Error creating wallet 'incogme-mediator-beta'
[2023-10-24 11:11:19]     at AskarWallet.createAndOpen (/www/node_modules/@aries-framework/askar/build/wallet/AskarWallet.js:118:19)
[2023-10-24 11:11:19]     at async WalletApi.createAndOpen (/www/node_modules/@aries-framework/core/build/wallet/WalletApi.js:63:9)
[2023-10-24 11:11:19]     at async WalletApi.initialize (/www/node_modules/@aries-framework/core/build/wallet/WalletApi.js:54:17)
[2023-10-24 11:11:19]     at async Agent.initialize (/www/node_modules/@aries-framework/core/build/agent/BaseAgent.js:89:13)
[2023-10-24 11:11:19]     at async Agent.initialize (/www/node_modules/@aries-framework/core/build/agent/Agent.js:124:9)
[2023-10-24 11:11:19]     at async createAgent (/www/build/agent.js:109:5) {
[2023-10-24 11:11:19]   [cause]: AriesAskarError: Backend error
[2023-10-24 11:11:19]   Caused by: error returned from database: database "postgres" does not exist
[2023-10-24 11:11:19]       at cb (/www/node_modules/@hyperledger/aries-askar-nodejs/build/NodeJSAriesAskar.js:44:39)
[2023-10-24 11:11:19]       at Object.<anonymous> (/www/node_modules/ffi-napi/lib/callback.js:66:27) {
[2023-10-24 11:11:19]     code: 1,
[2023-10-24 11:11:19]     extra: undefined
[2023-10-24 11:11:19]   }
[2023-10-24 
```

if I try to run it with local Postgres deployed to docker all works fine

Digital Ocean db

Regards!

**Comment by djleonskennedy** [comment]
Solution: `postgres` database should be created manualy (use PGAdmin)
