### ISSUE TITLE
Yarn install fails on node@18.18.2

### ISSUE THREAD

**Issue by outSH** [hyperledger/aries-framework-javascript#1617]
Running `yarn install` with `node@18.18.2` ends with error (because there's no binary of `node-bbs-signatures` for this node release). 

``` sh
[outsh@outshwinpc aries-framework-javascript]$ yarn install
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning Pattern ["@cheqd/ts-proto@cjs"] is trying to unpack in the same destination "/home/outsh/.cache/yarn/v6/npm-@cheqd-ts-proto-2.2.2-c0e808c6d438da7098a225ea24ee94db9822fa06-integrity/node_modules/@cheqd/ts-proto" as pattern ["@cheqd/ts-proto@^2.2.0"]. This could result in non-deterministic behavior, skipping.
[4/5] Linking dependencies...
warning " > @aries-framework/anoncreds-rs@0.4.2" has unmet peer dependency "@hyperledger/anoncreds-shared@^0.1.0".
warning " > @aries-framework/askar@0.4.2" has unmet peer dependency "@hyperledger/aries-askar-shared@^0.1.0".
warning " > @aries-framework/indy-sdk-to-askar-migration@0.4.2" has unmet peer dependency "@hyperledger/aries-askar-shared@^0.1.0".
warning " > @aries-framework/indy-vdr@0.4.2" has unmet peer dependency "@hyperledger/indy-vdr-shared@^0.1.0".
warning " > @aries-framework/react-native@0.4.2" has unmet peer dependency "react-native@^0.71.4".
warning " > @aries-framework/react-native@0.4.2" has unmet peer dependency "react-native-fs@^2.20.0".
warning " > @aries-framework/react-native@0.4.2" has unmet peer dependency "react-native-get-random-values@^1.8.0".
warning "workspace-aggregator-1f5d65f0-b0e8-4d50-8749-db867204a3ba > @aries-framework/react-native > react-native@0.71.7" has unmet peer dependency "react@18.2.0".
warning "workspace-aggregator-1f5d65f0-b0e8-4d50-8749-db867204a3ba > @aries-framework/react-native > react-native > metro-react-native-babel-transformer@0.73.9" has unmet peer dependency "@babel/core@*".
warning "workspace-aggregator-1f5d65f0-b0e8-4d50-8749-db867204a3ba > @aries-framework/react-native > react-native > react-shallow-renderer@16.15.0" has unmet peer dependency "react@^16.0.0 || ^17.0.0 || ^18.0.0".
warning "workspace-aggregator-1f5d65f0-b0e8-4d50-8749-db867204a3ba > @aries-framework/react-native > react-native > use-sync-external-store@1.2.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "workspace-aggregator-1f5d65f0-b0e8-4d50-8749-db867204a3ba > @aries-framework/core > @digitalcredentials/jsonld-signatures > isomorphic-webcrypto > expo-random@13.1.1" has unmet peer dependency "expo@*".
warning "workspace-aggregator-1f5d65f0-b0e8-4d50-8749-db867204a3ba > @aries-framework/core > @digitalcredentials/jsonld-signatures > isomorphic-webcrypto > react-native-securerandom@0.1.1" has unmet peer dependency "react-native@*".
warning "workspace-aggregator-1f5d65f0-b0e8-4d50-8749-db867204a3ba > @aries-framework/react-native > react-native > react-native-codegen > jscodeshift@0.13.1" has unmet peer dependency "@babel/preset-env@^7.1.6".
[5/5] Building fresh packages...
[1/13] ⠐ indy-sdk
[8/13] ⠐ @mattrglobal/node-bbs-signatures
[-/13] ⠐ waiting...
[6/13] ⠐ ffi-napi
warning Error running install script for optional dependency: "/home/outsh/projects/aries-framework-javascript/node_modules/@mattrglobal/node-bbs-signatures: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build=false
Arguments: 
Directory: /home/outsh/projects/aries-framework-javascript/node_modules/@mattrglobal/node-bbs-signatures
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.9
node-pre-gyp info using node@18.18.2 | linux | x64
node-pre-gyp info check checked for \"/home/outsh/projects/aries-framework-javascript/node_modules/@mattrglobal/node-bbs-signatures/native/index.node\" (not found)
node-pre-gyp http GET https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.15.0/node-v108-linux-x64.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.15.0/node-v108-linux-x64.tar.gz 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.15.0/node-v108-linux-x64.tar.gz
node-pre-gyp ERR! stack     at /home/outsh/projects/aries-framework-javascript/node_modules/@mattrglobal/node-bbs-signatures/node_modules/@mapbox/node-pre-gyp/lib/install.js:67:15
node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
node-pre-gyp ERR! System Linux 6.5.8-200.fc38.x86_64
node-pre-gyp ERR! command \"/home/outsh/.nvm/versions/node/v18.18.2/bin/node\" \"/home/outsh/projects/aries-framework-javascript/node_modules/@mattrglobal/node-bbs-signatures/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build=false\"
node-pre-gyp ERR! cwd /home/outsh/projects/aries-framework-javascript/node_modules/@mattrglobal/node-bbs-signatures
node-pre-gyp ERR! node -v v18.18.2
node-pre-gyp ERR! node-pre-gyp -v v1.0.9
node-pre-gyp ERR! not ok 
response status 404 Not Found on https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.15.0/node-v108-linux-x64.tar.gz"
info This module is OPTIONAL, you can safely ignore this error
warning Error running install script for optional dependency: "/home/outsh/projects/aries-framework-javascript/node_modules/@mattrglobal/bls12381-key-pair/node_modules/@mattrglobal/node-bbs-signatures: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build=false
Arguments: 
Directory: /home/outsh/projects/aries-framework-javascript/node_modules/@mattrglobal/bls12381-key-pair/node_modules/@mattrglobal/node-bbs-signatures
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.17.0
node-pre-gyp info using node@18.18.2 | linux | x64
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp info check checked for \"/home/outsh/projects/aries-framework-javascript/node_modules/@mattrglobal/bls12381-key-pair/node_modules/@mattrglobal/node-bbs-signatures/native/index.node\" (not found)
node-pre-gyp http GET https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.13.0/node-v108-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.13.0/node-v108-linux-x64.tar.gz
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/mattrglobal/node-bbs-signatures/releases/download/0.13.0/node-v108-linux-x64.tar.gz
node-pre-gyp ERR! stack     at PassThrough.<anonymous> (/home/outsh/projects/aries-framework-javascript/node_modules/node-pre-gyp/lib/install.js:142:27)
node-pre-gyp ERR! stack     at PassThrough.emit (node:events:529:35)
node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/home/outsh/projects/aries-framework-javascript/node_modules/needle/lib/needle.js:538:9)
node-pre-gyp ERR! stack     at Object.onceWrapper (node:events:632:26)
node-pre-gyp ERR! stack     at ClientRequest.emit (node:events:517:28)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (node:_http_client:541:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (node:events:517:28)
node-pre-gyp ERR! stack     at addChunk (node:internal/streams/readable:335:12)
node-pre-gyp ERR! System Linux 6.5.8-200.fc38.x86_64
node-pre-gyp ERR! command \"/home/outsh/.nvm/versions/node/v18.18.2/bin/node\" \"/home/outsh/projects/aries-framework-javascript/node_modules/@mattrglobal/bls12381-key-pair/node_modules/@mattrglobal/node-bbs-signatures/node_modules/.bin/node-pre-gyp\" \"install\" \"--fallback-to-build=false\"
node-pre-gyp ERR! cwd /home/outsh/projects/aries-framework-javascript/node_modules/@mattrglobal/bls12381-key-pair/node_modules/@mattrglobal/node-bbs-signatures
node-pre-gyp ERR! node -v v18.18.2
Done in 12.36s.
```

**Comment by berendsliedrecht** [comment]
This is a warning, not an error. It is not too clear, sadly.
