### ISSUE TITLE
Connection less credentials:  No corresponding recipient key found in mediator

### ISSUE THREAD

**Issue by sudddy** [hyperledger/aries-framework-javascript#1653]
Hello all,

**Question**: Connectionless credentials created via `createLegacyConnectionlessInvitation` unable to be claimed from mobile agent. The mediator says `No corresponding recipient key found` - I'm not sure what's wrong here?

STEP 1: I have issued the connection less credentials using the `createOffer` method. 
STEP 2:  A outbound message is send to the mediator without `RECIPIENT KEYS` or `ROUTING KEYS` 
```js 
DEBUG: Sending outbound message to service: {
  "messageId": "5936fc3e-0b8e-4870-9bdf-45b201edc610",
  "service": {
    "id": "#inline-0",
    "recipientKeys": "omitted...",
    "routingKeys": "omitted...",
    "serviceEndpoint": "http://localhost:6001"
  }
}
DEBUG: Pack outbound message https://didcomm.org/coordinate-mediation/1.0/keylist-update
DEBUG: Sending outbound message to endpoint 'http://localhost:6001' {
  "payload": {
    "protected": "eyJlbmMiOiJ4Y2hhY2hhMjBwb2x5MTMwNV9pZXRmIiwidHlwIjoiSldNLzEuMCIsImFsZyI6IkF1dGhjcnlwdCIsInJlY2lwaWVudHMiOlt7ImVuY3J5cHRlZF9rZXkiOiJTcDhuTFU2Wmxzdld3X2RlT0s3eVlRSmhqNF84d2M2X2x0bDRfMTlTU0pCZkE4Mzd6eWxWemx2RDRyR0oxVWFSIiwiaGVhZGVyIjp7ImtpZCI6IjJBV3Byc2ZKcEp6Zk5VaTNmSlc4R3BSMkRuWUg1WnZZWXY2bTRvalJyMVYzIiwic2VuZGVyIjoicWpQNUVVNXpqNGczdWstRmxBMmE5dmYzYS1rVVJ1TGZyTE53UFhHazdSbmNCMXhWTVRSOVp3QVJrNjZIS1BubGRJWjBMNUUzbWxFaHBvczJMQUVCb2NmYXRiVTctMl9qT1JPYlZjNk5keTFmaGtEd3VXdUc1N2xzbUxRIiwiaXYiOiJ6UUd1bk50NkJKSGxHZU9KUTlmN25FVXZTWWktbGVhcCJ9fV19",
    "ciphertext": "twWmNWhLl_iwt6k0HsIk34TfWb2tVSgfRWZePVo_D0N0B4XOZb0rfFxY3oVAZSSvKtHZwfPsMZN5h0mF875LWBkCQLlCvIYgQ8HpklYJVGAeKcLY0FdKxofsg1QC3vU4RcaEZyl13EuVyC8ErHuQQpWNWD1pUDmGfbsPfpoxUeEWxyVoOazjDNnZtWpve6voGJys8eznDOQ0X6J_bR5m1KUbQaiX4bkz0CRVemLVi7y9vhPpjGgKpJkGef_OIFl7baVmTdVa-rwuMpbCmWpv56GmS_8ewxrIIHLIhF4o2iQP5XD4RXmkv92eVN8NCA5Nywq1fk620BTiR_fpyal8yA",
    "iv": "ZE2fgZ17C20iRNIU",
    "tag": "hPlPQBvPqXvxQ86fvd6_rg"
  }
}
DEBUG: Response received {
  "responseMessage": "{\"protected\":\"eyJlbmMiOiJ4Y2hhY2hhMjBwb2x5MTMwNV9pZXRmIiwidHlwIjoiSldNLzEuMCIsImFsZyI6IkF1dGhjcnlwdCIsInJlY2lwaWVudHMiOlt7ImVuY3J5cHRlZF9rZXkiOiJnOThvZElWWWFIWXl2TFBaWmduS2tTclRNZVZqZklyakx5LXBIeGRWYTNhX3FSY1VfVjBqMjBiTkx3R0JBdTRoIiwiaGVhZGVyIjp7ImtpZCI6IkVtNldLY3Zod0FlWHlxSjk1dHdEak10UHRWUWQzZzN6QmZRS0h6RHplZTdOIiwic2VuZGVyIjoiNkVFS3hlWlFQbHhCVkdZWVUtcEJCeGdRYllFOFVncDZCdDZoWkRKLW1TR1pvQmhYLUlfQms4bmg3NDZwQjF6VjhkVzVyTk5lX0JyYkRJZGpGRC1BVFF4NVBuempnbzd3SFh4MWZ0b0pyY2JFUzdBVTZIVkZJYmNlTTBjIiwiaXYiOiJMRUFmNGdWLWo4VjJqMFc4YnhQMXp3YzZFZXdBTWQ2RSJ9fV19\",\"ciphertext\":\"gXKdERXV5Ykx8X11UHN-CBdWdSFd739vy_F4HKXUpKA98N96KVnze5YVmrKTrSxhj35gsPFnWeYOKZVnXJoqmOIv9n-P5btDLzS0LIosjGoNG99OExEKLot3I5PD6IXd5kImxEIjqICRDGJDgJtGgenmtl9Y7TndCsHm4yYpzaXpqzdQN1c9B4RpnLe8Tnb6DLNdl7IGATokw7LkYOZDj4fDAs5czAR-7UQ23qy1lbXTLlkIcWEna9QUuIEw7e359SIre9CouWN7DrvYvlPki9-Tq-Z7YGhRzNCIiy0ruTH2RY9h8pdkWI8Y2HjiZD1n_j9qPzu_Jouql_0IZFL1mXtHkiAg1e0wOqlIPIfNWKkya21YkxoihPrb-RKMoAKFSSQASCoLBgYXDELGTce5Kdwp\",\"iv\":\"umpQxjQlX2DGxaLa\",\"tag\":\"jAyibd4K9ISdCXr1TVpAkw\"}",
  "status": 200
}```


STEP 3:  Accepting the credentials in the Mobile Wallet 
```js
 DEBUG  DEBUG: No credential record found for offer, creating a new one
 DEBUG  DEBUG: Processing anoncreds credential offer for credential record cb72b264-a0cb-46f3-ab2b-42a3c3f786f2
 DEBUG  DEBUG: Saving credential record and emit offer-received event
 DEBUG  DEBUG: Received event CredentialStateChanged
 LOG  CREDENTIAL CAHNAGE {"credentialRecord": {"_tags": [Object], "autoAcceptCredential": undefined, "connectionId": undefined, "createdAt": "2023-11-28T04:24:19.862Z", "credentialAttributes": undefined, "credentials": [Array], "errorMessage": undefined, "id": "cb72b264-a0cb-46f3-ab2b-42a3c3f786f2", "linkedAttachments": undefined, "metadata": [Object], "protocolVersion": "v2", "revocationNotification": undefined, "state": "offer-received", "threadId": "fbbfc7b7-e7c5-41f9-a370-077c2249b598", "updatedAt": "2023-11-28T04:24:19.865Z"}, "previousState": null}
 INFO  INFO: Automatically sending request with autoAccept
 DEBUG  DEBUG: Getting credential definition 'did:indy:bcovrin:test:ABNwcnPB1tcAeNMts375Ui/anoncreds/v0/CLAIM_DEF/188132/latest' from ledger 'bcovrin:test'
 LOG  TRACE: Submitting get credential definition request for credential definition 'did:indy:bcovrin:test:ABNwcnPB1tcAeNMts375Ui/anoncreds/v0/CLAIM_DEF/188132/latest' to ledger 'bcovrin:test'
 LOG  TRACE: Found ledger id 'bcovrin:test' for did 'ABNwcnPB1tcAeNMts375Ui' in cache
 DEBUG  DEBUG: Getting transaction with seqNo '188132' from ledger 'bcovrin:test'
 LOG  TRACE: Submitting get transaction request to ledger 'bcovrin:test'
 DEBUG  DEBUG: Updating credential record cb72b264-a0cb-46f3-ab2b-42a3c3f786f2 to state request-sent (previous=offer-received)
 DEBUG  DEBUG: Creating outbound message context for message 6d311f13-45af-43cd-95fb-7cbb96fb7bab using connection-less exchange
 DEBUG  DEBUG: Looking for out-of-band record for message 6d311f13-45af-43cd-95fb-7cbb96fb7bab with thread id fbbfc7b7-e7c5-41f9-a370-077c2249b598
 DEBUG  DEBUG: No previous sent message in thread for outbound message 6d311f13-45af-43cd-95fb-7cbb96fb7bab, setting up routing
 DEBUG  DEBUG: Send outbound message {
  "message": {
    "@type": "https://didcomm.org/coordinate-mediation/1.0/keylist-update",
    "@id": "3c4e5b6f-e5d4-42d7-bf16-d461cb1190d7",
    "updates": [
      {
        "recipient_key": "did:key:z6MkpLYzN1R81MF6DFPrx4E9xmyNzwxhqKbrkFm6VE53Q6cH",
        "action": "add"
      }
    ]
  },
  "connectionId": "98f8ed65-8d59-4c4a-8b8d-34f07f69b74a"
}
 DEBUG  DEBUG: Retrieving services for connection '98f8ed65-8d59-4c4a-8b8d-34f07f69b74a' (Skippy Mediator) {
  "connection": {
    "_tags": {
      "connectionTypes": [
        "mediator"
      ],
      "did": "did:peer:1zQmVjsDHk8pFD2nNFnca699LBct3g6UTYms1zNZrwhGCVbA",
      "invitationDid": "did:peer:2.SeyJzIjoiaHR0cDovL2xvY2FsaG9zdDo2MDAxIiwidCI6ImRpZC1jb21tdW5pY2F0aW9uIiwicHJpb3JpdHkiOjAsInJlY2lwaWVudEtleXMiOlsiZGlkOmtleTp6Nk1rb0ZFS2Z1R3NoNWFNZHdKelY3SHA4eTZyWTV0WXlWUzZUa3hrRGpTYVJva0wjejZNa29GRUtmdUdzaDVhTWR3SnpWN0hwOHk2clk1dFl5VlM2VGt4a0RqU2FSb2tMIl0sInIiOltdfQ",
      "outOfBandId": "45e3a3f8-b5d7-4723-8231-da8c475e6a58",
      "role": "requester",
      "state": "completed",
      "theirDid": "did:peer:1zQmNvC3xaUD4q3EeRxm813LieErr7yrkkZLJFj4zqvcJtsj",
      "threadId": "834b6a9b-100c-4275-b581-f74882a0c9da"
    },
    "metadata": {
      "_internal/useDidKeysForProtocol": {
        "https://didcomm.org/coordinate-mediation/1.0": true
      }
    },
    "connectionTypes": [
      "mediator"
    ],
    "id": "98f8ed65-8d59-4c4a-8b8d-34f07f69b74a",
    "createdAt": "2023-11-28T02:25:33.986Z",
    "did": "did:peer:1zQmVjsDHk8pFD2nNFnca699LBct3g6UTYms1zNZrwhGCVbA",
    "invitationDid": "did:peer:2.SeyJzIjoiaHR0cDovL2xvY2FsaG9zdDo2MDAxIiwidCI6ImRpZC1jb21tdW5pY2F0aW9uIiwicHJpb3JpdHkiOjAsInJlY2lwaWVudEtleXMiOlsiZGlkOmtleTp6Nk1rb0ZFS2Z1R3NoNWFNZHdKelY3SHA4eTZyWTV0WXlWUzZUa3hrRGpTYVJva0wjejZNa29GRUtmdUdzaDVhTWR3SnpWN0hwOHk2clk1dFl5VlM2VGt4a0RqU2FSb2tMIl0sInIiOltdfQ",
    "theirLabel": "Skippy Mediator",
    "state": "completed",
    "role": "requester",
    "autoAcceptConnection": true,
    "threadId": "834b6a9b-100c-4275-b581-f74882a0c9da",
    "protocol": "https://didcomm.org/didexchange/1.0",
    "outOfBandId": "45e3a3f8-b5d7-4723-8231-da8c475e6a58",
    "updatedAt": "2023-11-28T02:25:39.211Z",
    "theirDid": "did:peer:1zQmNvC3xaUD4q3EeRxm813LieErr7yrkkZLJFj4zqvcJtsj"
  }
}
 DEBUG  DEBUG: Resolving services for connection theirDid did:peer:1zQmNvC3xaUD4q3EeRxm813LieErr7yrkkZLJFj4zqvcJtsj.
 DEBUG  DEBUG: resolving didUrl did:peer:1zQmNvC3xaUD4q3EeRxm813LieErr7yrkkZLJFj4zqvcJtsj
 DEBUG  DEBUG: Retrieved 4 services for message to connection '98f8ed65-8d59-4c4a-8b8d-34f07f69b74a'(Skippy Mediator)' {
  "hasQueueService": false
}
 DEBUG  DEBUG: resolving didUrl did:peer:1zQmVjsDHk8pFD2nNFnca699LBct3g6UTYms1zNZrwhGCVbA
 DEBUG  DEBUG: Sending outbound message to service: {
  "messageId": "3c4e5b6f-e5d4-42d7-bf16-d461cb1190d7",
  "service": {
    "id": "#inline-0",
    "recipientKeys": "omitted...",
    "routingKeys": "omitted...",
    "serviceEndpoint": "http://localhost:6001"
  }
}
 DEBUG  DEBUG: Pack outbound message https://didcomm.org/coordinate-mediation/1.0/keylist-update
 DEBUG  DEBUG: Sending outbound message to endpoint 'http://localhost:6001' {
  "payload": {
    "protected": "eyJlbmMiOiJ4Y2hhY2hhMjBwb2x5MTMwNV9pZXRmIiwidHlwIjoiSldNLzEuMCIsImFsZyI6IkF1dGhjcnlwdCIsInJlY2lwaWVudHMiOlt7ImVuY3J5cHRlZF9rZXkiOiJsT3drb0dkS1R1RDM4S2tqU2l6S0ctSV9LUTFqY0dFS3pfRTdvU3dWUFBSNzNsQ3VwUFQ0S3R0OTNYYTJLMU5mIiwiaGVhZGVyIjp7ImtpZCI6IjNTRmpKdDM2ZFRBNU5hOTJqQlNIU2ZRNHZZN1JtTkJZRG4zTk5XdU5zQTI1Iiwic2VuZGVyIjoiclZoRWRLWktrczRxbE5oTTRZRUdhVW1yUUdnWWRuSWJLbzNWN3g5YVJrdnNxaFRnaGQxa2VqT0UxN3F6WWh3THJYbFNFY19QTWcwTmF2SmtFWmFGanN0ZnJwbEtZTThicUtXOTZyZ0Q4dWVEZThtd1VzMV9ISGRDSnZZIiwiaXYiOiJ4Z2hHLWx2UHE2dEkwWnpFczBWb0JMUjNfNmlUUTJhVSJ9fV19",
    "ciphertext": "k63pjb0m1wyQdUn0w5sioqYWgVWrwv2c0bZU3-EpmjWk1CkjZdQK5ja4aqUwpgUiP-A38Mjjv3zt4SFxqH7rwPDD5tMHueCDy5cdfB_EFOa4z575k9IPkBcmzajNX4qBCEv0RbcbM6WX3oZ40MbYMylBXVcBLGhvWXLbTwj4Iy7JHtvqL24IrVif1TJWGbvMVrmDpFKMTBvMGsbUjNkRm61Z8znjHir-rLwBTM9sl5D-UIJkhs6wsOrRktf7SVl764h1DW6QnJOyuL2Hc96u0Ls_LeXWb1qvcjE35wn7zrXwe2KQFfcHm8Na7JkNpIMMWPT3Xue64Tv1ufkTqrrTjA",
    "iv": "Gy7tDpV4jb9UJL-i",
    "tag": "3IySqXQ2yXjBvAKaWN2Raw"
  }
}
 DEBUG  DEBUG: Response received {
  "responseMessage": "Error processing message",
  "status": 500
}
```

STEP4 :  Mediator Error

``` js 
kippy_mediator_service  | ERROR: Error while decrypting message {
skippy_mediator_service  |   "error": {
skippy_mediator_service  |     "name": "WalletError",
skippy_mediator_service  |     "message": "No corresponding recipient key found",
skippy_mediator_service  |     "stack": "WalletError: No corresponding recipient key found\n    at AskarWallet.unpack (/app/node_modules/@aries-framework/askar/build/wallet/AskarBaseWallet.js:350:19)\n    at async EnvelopeService.unpackMessage (/app/node_modules/@aries-framework/core/build/agent/EnvelopeService.js:51:34)\n    at async MessageReceiver.decryptMessage (/app/node_modules/@aries-framework/core/build/agent/MessageReceiver.js:133:20)\n    at async MessageReceiver.receiveEncryptedMessage (/app/node_modules/@aries-framework/core/build/agent/MessageReceiver.js:87:34)\n    at async MessageReceiver.receiveMessage (/app/node_modules/@aries-framework/core/build/agent/MessageReceiver.js:67:17)\n    at async /app/node_modules/@aries-framework/node/build/transport/HttpInboundTransport.js:58:17"
skippy_mediator_service  |   },
skippy_mediator_service  |   "encryptedMessage": {
skippy_mediator_service  |     "protected": "eyJlbmMiOiJ4Y2hhY2hhMjBwb2x5MTMwNV9pZXRmIiwidHlwIjoiSldNLzEuMCIsImFsZyI6IkF1dGhjcnlwdCIsInJlY2lwaWVudHMiOlt7ImVuY3J5cHRlZF9rZXkiOiIyQzB5endWRVcwWnVDUzQyd2hSRHVPb0dGaTV3X0FDTmRRd2VZS05YTTRIV1REMDAwLUxOcEhxM1J1NnUtVE5RIiwiaGVhZGVyIjp7ImtpZCI6IjNTRmpKdDM2ZFRBNU5hOTJqQlNIU2ZRNHZZN1JtTkJZRG4zTk5XdU5zQTI1Iiwic2VuZGVyIjoieWJGbjVoVWcwSFpNMF9KTC1HTGtjTUgzcHRsZF9UR3ktOW1TdnZ2TkdFMElLRDFhaGp0MVl1QXZnTEVnUGtTcWljX3JBZVp1dWhES2tzUzBLaVFNbzZVekpvVmlvSFhsU1lNTjBvU2ptbmlVWGhZd2hyY190Z0JRVmE0IiwiaXYiOiJKV0NQb3A0SDJTbjNGYkNFMnF0THlXbDNjRE1QdldJMSJ9fV19",
skippy_mediator_service  |     "ciphertext": "LP0dwSr-_T5HVajdkaIf8_1hCKoCoHrq31a4bPcoidi8v9I3fWXNIxlSV_-RZ-5Shzlci_QO19EJT26w04STpFJBqraHkogSpaaLKQ1rVp8ZqSU0z9bVq9tU3TgqIeZVcp-DvoX9fZBKzGYrvwcfegu3he81ylIsdREkW9trobz5pd2jhTyNPrzFnMFBHMfiRw",
skippy_mediator_service  |     "iv": "aRynOCnlqQUqSEjk",
skippy_mediator_service  |     "tag": "PSam2FB8I_e9rLv5ZuRK6Q"
skippy_mediator_service  |   },
skippy_mediator_service  |   "errorMessage": "No corresponding recipient key found"
skippy_mediator_service  | }
skippy_mediator_service  | ERROR: Error processing inbound message: No corresponding recipient key found {
skippy_mediator_service  |   "name": "WalletError",
skippy_mediator_service  |   "message": "No corresponding recipient key found",
skippy_mediator_service  |   "stack": "WalletError: No corresponding recipient key found\n    at AskarWallet.unpack (/app/node_modules/@aries-framework/askar/build/wallet/AskarBaseWallet.js:350:19)\n    at async EnvelopeService.unpackMessage (/app/node_modules/@aries-framework/core/build/agent/EnvelopeService.js:51:34)\n    at async MessageReceiver.decryptMessage (/app/node_modules/@aries-framework/core/build/agent/MessageReceiver.js:133:20)\n    at async MessageReceiver.receiveEncryptedMessage (/app/node_modules/@aries-framework/core/build/agent/MessageReceiver.js:87:34)\n    at async MessageReceiver.receiveMessage (/app/node_modules/@aries-framework/core/build/agent/MessageReceiver.js:67:17)\n    at async /app/node_modules/@aries-framework/node/build/transport/HttpInboundTransport.js:58:17"
skippy_mediator_service  | }
skippy_mediator_service  | ERROR: Error while decrypting message {
skippy_mediator_service  |   "error": {
skippy_mediator_service  |     "name": "WalletError",
skippy_mediator_service  |     "message": "No corresponding recipient key found",
skippy_mediator_service  |     "stack": "WalletError: No corresponding recipient key found\n    at AskarWallet.unpack (/app/node_modules/@aries-framework/askar/build/wallet/AskarBaseWallet.js:350:19)\n    at async EnvelopeService.unpackMessage (/app/node_modules/@aries-framework/core/build/agent/EnvelopeService.js:51:34)\n    at async MessageReceiver.decryptMessage (/app/node_modules/@aries-framework/core/build/agent/MessageReceiver.js:133:20)\n    at async MessageReceiver.receiveEncryptedMessage (/app/node_modules/@aries-framework/core/build/agent/MessageReceiver.js:87:34)\n    at async MessageReceiver.receiveMessage (/app/node_modules/@aries-framework/core/build/agent/MessageReceiver.js:67:17)\n    at async WebSocket.<anonymous> (/app/node_modules/@aries-framework/node/build/transport/WsInboundTransport.js:77:17)"
skippy_mediator_service  |   },
skippy_mediator_service  |   "encryptedMessage": {
skippy_mediator_service  |     "protected": "eyJlbmMiOiJ4Y2hhY2hhMjBwb2x5MTMwNV9pZXRmIiwidHlwIjoiSldNLzEuMCIsImFsZyI6IkF1dGhjcnlwdCIsInJlY2lwaWVudHMiOlt7ImVuY3J5cHRlZF9rZXkiOiJYZjU1YmpUVGdRcVNUeTdVZC1YcVFGQXZ3UDQxN1puM2piVFFCT3FSeWlRRWl0bGxtbnVFUUVvcS1fbUt1M3dsIiwiaGVhZGVyIjp7ImtpZCI6IjNTRmpKdDM2ZFRBNU5hOTJqQlNIU2ZRNHZZN1JtTkJZRG4zTk5XdU5zQTI1Iiwic2VuZGVyIjoidnI5bElfeW5mYnNocU9VZHZxWlJ0ekJhZG1RNEo3d3VlMDN1MHlwaWszUnhPLXZicHZ5TVBRQVJ5WTBCRkNDS21aSWN4bVBzaEZmTkd1bThfb1NiVXhvQVhvUnlaX3hnYVlabG1xWnJoRUpXYWlBeWd0YUdQQmlINXlzIiwiaXYiOiJ0S3prRG10czdsTWNoem1sVmM4eGFRRDk1YjJKbUJsVSJ9fV19",
skippy_mediator_service  |     "ciphertext": "bgLHCQAfbrFEhsmKvM6uVVvu1OY_iktDjBRS2t42mghGzZ-pWOFBt2R9m58E0RVeZGSyuYLh5JvFjkdrwfJClfHxnZ_dSeRUHmROR668P5Z_zDiiQnwE5cVMWqSnsLdPn8E0aiqih4R5nQX8Uq2fMW3cl0TWvKM6g7AgR91fTuB-hqZVLWHy4rOlWRN6w1uyysw_SmcIgaGi5J4Qlrld",
skippy_mediator_service  |     "iv": "zVvK-EUDeQ4JpGhZ",
skippy_mediator_service  |     "tag": "nrnaRGFFU9QrAEin6EXAdQ"
skippy_mediator_service  |   },
skippy_mediator_service  |   "errorMessage": "No corresponding recipient key found"
skippy_mediator_service  | }
skippy_mediator_service  | ERROR: Error processing message: WalletError: No corresponding recipient key found
skippy_mediator_service  | DEBUG: Agent received message
skippy_mediator_service  | ERROR: Error while decrypting message {
skippy_mediator_service  |   "error": {
skippy_mediator_service  |     "name": "WalletError",
skippy_mediator_service  |     "message": "No corresponding recipient key found",
skippy_mediator_service  |     "stack": "WalletError: No corresponding recipient key found\n    at AskarWallet.unpack (/app/node_modules/@aries-framework/askar/build/wallet/AskarBaseWallet.js:350:19)\n    at async EnvelopeService.unpackMessage (/app/node_modules/@aries-framework/core/build/agent/EnvelopeService.js:51:34)\n    at async MessageReceiver.decryptMessage (/app/node_modules/@aries-framework/core/build/agent/MessageReceiver.js:133:20)\n    at async MessageReceiver.receiveEncryptedMessage (/app/node_modules/@aries-framework/core/build/agent/MessageReceiver.js:87:34)\n    at async MessageReceiver.receiveMessage (/app/node_modules/@aries-framework/core/build/agent/MessageReceiver.js:67:17)\n    at async /app/node_modules/@aries-framework/node/build/transport/HttpInboundTransport.js:58:17"
skippy_mediator_service  |   },
skippy_mediator_service  |   "encryptedMessage": {
skippy_mediator_service  |     "protected": "eyJlbmMiOiJ4Y2hhY2hhMjBwb2x5MTMwNV9pZXRmIiwidHlwIjoiSldNLzEuMCIsImFsZyI6IkF1dGhjcnlwdCIsInJlY2lwaWVudHMiOlt7ImVuY3J5cHRlZF9rZXkiOiJsT3drb0dkS1R1RDM4S2tqU2l6S0ctSV9LUTFqY0dFS3pfRTdvU3dWUFBSNzNsQ3VwUFQ0S3R0OTNYYTJLMU5mIiwiaGVhZGVyIjp7ImtpZCI6IjNTRmpKdDM2ZFRBNU5hOTJqQlNIU2ZRNHZZN1JtTkJZRG4zTk5XdU5zQTI1Iiwic2VuZGVyIjoiclZoRWRLWktrczRxbE5oTTRZRUdhVW1yUUdnWWRuSWJLbzNWN3g5YVJrdnNxaFRnaGQxa2VqT0UxN3F6WWh3THJYbFNFY19QTWcwTmF2SmtFWmFGanN0ZnJwbEtZTThicUtXOTZyZ0Q4dWVEZThtd1VzMV9ISGRDSnZZIiwiaXYiOiJ4Z2hHLWx2UHE2dEkwWnpFczBWb0JMUjNfNmlUUTJhVSJ9fV19",
skippy_mediator_service  |     "ciphertext": "k63pjb0m1wyQdUn0w5sioqYWgVWrwv2c0bZU3-EpmjWk1CkjZdQK5ja4aqUwpgUiP-A38Mjjv3zt4SFxqH7rwPDD5tMHueCDy5cdfB_EFOa4z575k9IPkBcmzajNX4qBCEv0RbcbM6WX3oZ40MbYMylBXVcBLGhvWXLbTwj4Iy7JHtvqL24IrVif1TJWGbvMVrmDpFKMTBvMGsbUjNkRm61Z8znjHir-rLwBTM9sl5D-UIJkhs6wsOrRktf7SVl764h1DW6QnJOyuL2Hc96u0Ls_LeXWb1qvcjE35wn7zrXwe2KQFfcHm8Na7JkNpIMMWPT3Xue64Tv1ufkTqrrTjA",
skippy_mediator_service  |     "iv": "Gy7tDpV4jb9UJL-i",
skippy_mediator_service  |     "tag": "3IySqXQ2yXjBvAKaWN2Raw"
skippy_mediator_service  |   },
skippy_mediator_service  |   "errorMessage": "No corresponding recipient key found"
skippy_mediator_service  | }
skippy_mediator_service  | ERROR: Error processing inbound message: No corresponding recipient key found {
skippy_mediator_service  |   "name": "WalletError",
skippy_mediator_service  |   "message": "No corresponding recipient key found",
skippy_mediator_service  |   "stack": "WalletError: No corresponding recipient key found\n    at AskarWallet.unpack (/app/node_modules/@aries-framework/askar/build/wallet/AskarBaseWallet.js:350:19)\n    at async EnvelopeService.unpackMessage (/app/node_modules/@aries-framework/core/build/agent/EnvelopeService.js:51:34)\n    at async MessageReceiver.decryptMessage (/app/node_modules/@aries-framework/core/build/agent/MessageReceiver.js:133:20)\n    at async MessageReceiver.receiveEncryptedMessage (/app/node_modules/@aries-framework/core/build/agent/MessageReceiver.js:87:34)\n    at async MessageReceiver.receiveMessage (/app/node_modules/@aries-framework/core/build/agent/MessageReceiver.js:67:17)\n    at async /app/node_modules/@aries-framework/node/build/transport/HttpInboundTransport.js:58:17"
skippy_mediator_service  | }
```

**Comment by sudddy** [comment]
Issue:  Used different mediator links (every time) inside the mobile wallet due to development constraints. 
Fix:  Created a new wallet and used the mediator link - it worked.
