### ISSUE TITLE
Running yarn install fails with error: ld: library not found for -lindy

### ISSUE THREAD

**Issue by DavidClawson** [hyperledger/aries-framework-javascript#221]
Note that the overall intent here is to be able to build the project to a .tgz file for use in a React Native app. 

Hardware: Intel i7 MacBook Pro, M1 Mac Mini. Both running Big Sur. 
**Steps** 
1. `git clone https://github.com/hyperledger/aries-framework-javascript`
2.  `yarn install`
yields the error (among other output):
`ld: library not found for -lindy`

**What I've tried:**
`yarn install indy-sdk` and `yarn install rn-indy-sdk`
Note that if I use `install`, I get the error: 
`error "install" has been replaced with "add" to add new dependencies. Run "yarn add indy-sdk" instead.`
Using `yarn add indy-sdk` or `yarn add rn-indy-sdk` both yield the same error from before: 
`ld: library not found for -lindy`

**Full output here:** 

```
david@david aries-framework-javascript % yarn add indy-sdk    
yarn add v1.22.10
warning ../../package.json: No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
error /Users/david/Desktop/aries-framework-javascript/node_modules/indy-sdk: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/david/Desktop/aries-framework-javascript/node_modules/indy-sdk
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@12.15.0 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/Users/david/Desktop/aries-framework-javascript/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/david/Desktop/aries-framework-javascript/node_modules/indy-sdk/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/david/Desktop/aries-framework-javascript/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/david/.node-gyp/12.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/david/.node-gyp/12.15.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/david/Desktop/aries-framework-javascript/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/david/.node-gyp/12.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/david/Desktop/aries-framework-javascript/node_modules/indy-sdk',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/indynodejs/src/indy.o
../src/indy.cc:234:24: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
                tuple->Set(0, Nan::New<v8::Number>(icb->handle0));
                       ^
/Users/david/.node-gyp/12.15.0/include/node/v8.h:3411:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/david/.node-gyp/12.15.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/indy.cc:235:24: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
                tuple->Set(1, Nan::New<v8::Number>(icb->u32int0));
                       ^
/Users/david/.node-gyp/12.15.0/include/node/v8.h:3411:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/david/.node-gyp/12.15.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/indy.cc:243:24: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
                tuple->Set(0, toJSString(icb->str0));
                       ^
/Users/david/.node-gyp/12.15.0/include/node/v8.h:3411:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/david/.node-gyp/12.15.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/indy.cc:244:24: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
                tuple->Set(1, Nan::New<v8::Number>(icb->i64int0));
                       ^
/Users/david/.node-gyp/12.15.0/include/node/v8.h:3411:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/david/.node-gyp/12.15.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/indy.cc:252:24: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
                tuple->Set(0, toJSString(icb->str0));
                       ^
/Users/david/.node-gyp/12.15.0/include/node/v8.h:3411:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/david/.node-gyp/12.15.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/indy.cc:253:24: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
                tuple->Set(1, Nan::NewBuffer(icb->buffer0data, icb->buffer0len).ToLocalChecked());
                       ^
/Users/david/.node-gyp/12.15.0/include/node/v8.h:3411:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/david/.node-gyp/12.15.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/indy.cc:258:24: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
                tuple->Set(0, toJSString(icb->str0));
                       ^
/Users/david/.node-gyp/12.15.0/include/node/v8.h:3411:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/david/.node-gyp/12.15.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/indy.cc:259:24: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
                tuple->Set(1, toJSString(icb->str1));
                       ^
/Users/david/.node-gyp/12.15.0/include/node/v8.h:3411:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/david/.node-gyp/12.15.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/indy.cc:264:24: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
                tuple->Set(0, toJSString(icb->str0));
                       ^
/Users/david/.node-gyp/12.15.0/include/node/v8.h:3411:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/david/.node-gyp/12.15.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/indy.cc:265:24: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
                tuple->Set(1, toJSString(icb->str1));
                       ^
/Users/david/.node-gyp/12.15.0/include/node/v8.h:3411:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/david/.node-gyp/12.15.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/indy.cc:266:24: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
                tuple->Set(2, Nan::New<v8::Number>(icb->timestamp0));
                       ^
/Users/david/.node-gyp/12.15.0/include/node/v8.h:3411:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/david/.node-gyp/12.15.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/indy.cc:271:24: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
                tuple->Set(0, toJSString(icb->str0));
                       ^
/Users/david/.node-gyp/12.15.0/include/node/v8.h:3411:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/david/.node-gyp/12.15.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/indy.cc:272:24: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
                tuple->Set(1, toJSString(icb->str1));
                       ^
/Users/david/.node-gyp/12.15.0/include/node/v8.h:3411:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/david/.node-gyp/12.15.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/indy.cc:273:24: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
                tuple->Set(2, toJSString(icb->str2));
                       ^
/Users/david/.node-gyp/12.15.0/include/node/v8.h:3411:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/david/.node-gyp/12.15.0/include/node/v8config.h:311:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
14 warnings generated.
  SOLINK_MODULE(target) Release/indynodejs.node
ld: library not found for -lindy
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/indynodejs.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/david/Desktop/aries-framework-javascript/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 20.3.0
gyp ERR! command "/usr/local/bin/node" "/Users/david/Desktop/aries-framework-javascript/node_modules/indy-sdk/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/david/Desktop/aries-framework-javascript/node_modules/indy-sdk
gyp ERR! node -v v12.15.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by TimoGlastra** [comment]
This is a bit of an unfortunate error, and one of the reasons we should release AFJ on NPM ASAP. This is related to indy-sdk for NodeJS and therefore shouldn't be an issue for RN.

Did you install the libindy binaries? If not please see [Prerequisites](https://github.com/hyperledger/aries-framework-javascript#prerequisites). Otherwise this section from the troubleshooting page may be of help? https://github.com/hyperledger/aries-framework-javascript/blob/main/TROUBLESHOOTING.md#unable-to-find-libindydylib

Let me know if that works. Otherwise I'll take a closer look

**Comment by DavidClawson** [comment]
That's great feedback. I got through some of the Prerequisites in the past, thinking I was done. I went through them again, and had mixed success.

**Steps taken:** 

1.  Downloaded [https://repo.sovrin.org/macos/libindy/stable/1.16.0/](https://repo.sovrin.org/macos/libindy/stable/1.16.0/)
2. Ran `otool -L libindy.dylib` to get the needed versions of libsodium, zeromq, openssl
3. Downloaded the latest build of [Libsodium](https://download.libsodium.org/libsodium/releases/)
4. [Installed Libsodium](https://doc.libsodium.org/installation) - Note that there was a comment about pointing the dynamic linker to the library that I didn't figure out 100%
5. ZeroMQ was easy: `brew install zmq`
6. OpenSSL: `brew install openssl` (also did the PATH export)
7. Added the path to lib folder to `LIBRARY_PATH` in the env variables

**Success!** I was able to run `yarn build` and `yarn pack` and get the .tgz archive.

Next up, and probably separate issues: 

When I run `docker-compose -f docker/docker-compose-mediators.yml -f docker/docker-compose-mediators-ngrok.yml up -d`
I get: 
 ```
=> ERROR [base 7/8] RUN apt-get update -y && apt-get install -y --allow-unauthenticated     libindy     nodejs                                                        6.1s
------                                                                                                                                                                      
 > [base 7/8] RUN apt-get update -y && apt-get install -y --allow-unauthenticated     libindy     nodejs:                                                                   
#10 1.776 Get:1 https://deb.nodesource.com/node_12.x bionic InRelease [4584 B]                                                                                              
#10 1.838 Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic InRelease                                                                                                       
#10 1.992 Get:3 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease [88.7 kB]                                                                                     
#10 1.999 Get:4 https://deb.nodesource.com/node_12.x bionic/main arm64 Packages [766 B]                                                                                     
#10 2.065 Get:5 https://repo.sovrin.org/sdk/deb bionic InRelease [13.3 kB]
#10 2.558 Get:6 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease [74.6 kB]
#10 2.817 Get:7 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease [88.7 kB]
#10 3.040 Get:8 http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe arm64 Packages [1908 kB]
#10 3.943 Get:9 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64 Packages [1547 kB]
#10 4.180 Get:10 http://ports.ubuntu.com/ubuntu-ports bionic-security/universe arm64 Packages [1220 kB]
#10 4.376 Get:11 http://ports.ubuntu.com/ubuntu-ports bionic-security/main arm64 Packages [1166 kB]
#10 4.734 Get:12 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
#10 4.889 Get:13 https://dl.yarnpkg.com/debian stable/main arm64 Packages [10.2 kB]
#10 4.939 Get:14 https://dl.yarnpkg.com/debian stable/main all Packages [10.2 kB]
#10 4.952 Fetched 6149 kB in 5s (1299 kB/s)
#10 4.952 Reading package lists...
#10 5.449 Reading package lists...
#10 5.897 Building dependency tree...
#10 5.974 Reading state information...
#10 6.017 E: Unable to locate package libindy
```
I also tried to run: `./scripts/run-mediator.sh mediator01`

and got this error: 

```
Error: dlopen(/Users/david/Desktop/aries-framework-javascript/node_modules/indy-sdk/build/Release/indynodejs.node, 1): Library not loaded: /Users/jenkins/workspace/indy-sdk_indy-sdk-cd_rc/libindy/target/release/deps/libindy.dylib
  Referenced from: /Users/david/Desktop/aries-framework-javascript/node_modules/indy-sdk/build/Release/indynodejs.node
  Reason: image not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at bindings (/Users/david/Desktop/aries-framework-javascript/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/david/Desktop/aries-framework-javascript/node_modules/indy-sdk/src/indyBinding.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
error Command failed with exit code 1.
```
I searched for the error, and found that the `libindy.dylib` file needed to be in `/usr/local/lib/`. I just copied it from another location into that directory, and when I re-ran the script I got an error from MacOS that wouldn't let me run it from an unknown source. I couldn't just go to the System Preferences and allow it, I found that I would have had to go into the CLI for the security settings and essentially whitelist that library file. At that point, I figured that I was a little beyond what we'd expect a regular user to do, and so I stopped. 

Thanks for your help, some progress is good!

**Comment by TimoGlastra** [comment]
The process can be quite cumbersome. Sadly, almost all of it is related to Indy. For macOS (pre-silicon) we have some troubleshooting guidelines as that's what we all use for development.

We don't have any silicon macs, so if you'd be able to help with this that'd be much appreciated. But that's not something I can assist with sadly :(

**Comment by shoebsd31** [comment]
I am getting the following error while installing the pre-requisites
I am using ubuntu and I executed the following statement :
`sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb (bionic) stable"`
It is not able to get : **https://repo.sovrin.org/sdk/deb (bionic) Release**
`sudo add-apt-repository "deb https://repo.sovrin.org/sdk/deb (bionic) stable"
Hit:1 http://at.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://at.archive.ubuntu.com/ubuntu focal-updates InRelease              
Hit:3 http://at.archive.ubuntu.com/ubuntu focal-backports InRelease            
Hit:4 http://dl.google.com/linux/chrome/deb stable InRelease                   
Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]      
Hit:6 https://packages.microsoft.com/repos/azure-cli focal InRelease           
Ign:8 https://repo.sovrin.org/sdk/deb (bionic) InRelease                       
Err:9 https://repo.sovrin.org/sdk/deb (bionic) Release
  404  Not Found [IP: 3.17.126.236 443]
Get:7 https://packages.cloud.google.com/apt kubernetes-xenial InRelease [9.383 B]
Err:7 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B57C5C2836F4BEB NO_PUBKEY FEEA9169307EA071
Reading package lists... Done
E: The repository 'https://repo.sovrin.org/sdk/deb (bionic) Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B57C5C2836F4BEB NO_PUBKEY FEEA9169307EA071
`

Is there something specific I need to do ?. Also in the documentation it would be great if we could say something like : 
**Replace the following before executing the code** and then the commands. People tend to read upside down, so at times execute the command first :) and then have to cleanup the source list.

**Comment by TimoGlastra** [comment]
I don't have linux. @blu3beri did you have this problem when installing Indy / could you verify if you have the same issue with reinstalling?

**Comment by blu3beri** [comment]
Unfortunately, I do not have a Debian based Distribution. I will try it on my Virtual Box with Debian to see if I can figure it out. I'd also suggest to make a seperate issue, since it does not seem related to the first issue.

**Comment by blu3beri** [comment]
After some small testing I have found out that it means that the repository does not support you version of Debian. Based on [Does not have a Release file](https://askubuntu.com/questions/866901/what-can-i-do-if-a-repository-ppa-does-not-have-a-release-file). I would recommend creating an issue at the indy-sdk repo as that is where this issue resides.

**Comment by blu3beri** [comment]
@shoebsd31 I made a gist for installing everything to work with AFJ. It was tested on the newest version of POP!_OS (debian based) [Check it here!](https://gist.github.com/blu3beri/a6ce6c4b0723fc10a2abc8682d5fde11)

**Comment by shoebsd31** [comment]
> @shoebsd31 I made a gist for installing everything to work with AFJ. It was tested on the newest version of POP!_OS (debian based) [Check it here!](https://gist.github.com/blu3beri/a6ce6c4b0723fc10a2abc8682d5fde11)

Thanks :)

**Comment by blu3beri** [comment]
> > @shoebsd31 I made a gist for installing everything to work with AFJ. It was tested on the newest version of POP!_OS (debian based) [Check it here!](https://gist.github.com/blu3beri/a6ce6c4b0723fc10a2abc8682d5fde11)
> 
> Thanks, Unfortunately it doesn't work for me. I have ubuntu version : release 20.4 

Oh which step it went wrong? Do you have the error output by any chance?

**Comment by shoebsd31** [comment]
i couldn't run **cargo build** command
I get this error :
![image](https://user-images.githubusercontent.com/5415085/113686691-d0c28780-96c7-11eb-9e6b-f769b89da738.png)

**Comment by blu3beri** [comment]
Ah yeah that was my fault. Within the Indy-sdk you should cd into ```libindy```. 

My bad!

**Comment by shoebsd31** [comment]
> Ah yeah that was my fault. Within the Indy-sdk you should cd into `libindy`.
> 
> My bad!
> 
> edit: I've updated the setup gist for debian based systems so you can follow that one (everything should be fine now).

that worked :) thanks !!!

**Comment by TimoGlastra** [comment]
Closing, if new issues arise we can open new issues
