### ISSUE TITLE
Error packing message in iphone

### ISSUE THREAD

**Issue by standlove** [hyperledger/aries-framework-javascript#522]
Hi,

When testing scanning invitation code in iphone, I got this error:
```
DEBUG: Sending outbound message to service with id 08e1e257-f5f2-44d7-b851-97cb70f32cc2-invitation failed with the following error: {
  "message": "Error packing message",
  "error": {}
}
```

It's also related to this: https://github.com/hyperledger/aries-mobile-agent-react-native/issues/112

Can you help check? Thanks.

**Comment by TimoGlastra** [comment]
The error is kinda hard to debug currently. I've made a PR that should make the errors being logged much more verbose: https://github.com/hyperledger/aries-framework-javascript/pull/524

Once that is merged could you try updating to the latest version? (and make sure you have supplied a `ConsoleLogger` on startup)

**Comment by standlove** [comment]
Hi, @TimoGlastra 

This is the updated error. Can you help check?  Thanks

```
 DEBUG  DEBUG: Sending outbound message to service with id cccecfc7-e593-4302-9e6e-15618d6a968b-invitation failed with the following error: {
  "message": "Error packing message",
  "error": {
    "name": "WalletError",
    "message": "Error packing message",
    "stack": "Error\n    at captureStackTrace (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:126222:32)\n    at BaseError (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:126264:22)\n    at construct (native)\n    at _createSuperInternal (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:126141:406)\n    at call (native)\n    at BaseError (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:126172:26)\n    at construct (native)\n    at _createSuperInternal (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:126110:406)\n    at call (native)\n    at AriesFrameworkError (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:126130:25)\n    at construct (native)\n    at _createSuperInternal (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:127994:406)\n    at call (native)\n    at WalletError (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:128014:25)\n    at pack$ (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:127720:82)\n    at call (native)\n    at tryCatch (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:24037:23)\n    at invoke (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:24207:32)\n    at anonymous (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:24079:30)\n    at call (native)\n    at tryCatch (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:24037:23)\n    at invoke (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:24109:30)\n    at anonymous (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:24121:21)\n    at tryCallOne (/Users/distiller/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:53:16)\n    at anonymous (/Users/distiller/hermes/build_iphoneos/lib/InternalBytecode/InternalBytecode.js:139:27)\n    at apply (native)\n    at anonymous (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:29406:26)\n    at _callTimer (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:29302:17)\n    at _callReactNativeMicrotasksPass (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:29341:17)\n    at callReactNativeMicrotasks (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:29551:44)\n    at __callReactNativeMicrotasks (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:3057:46)\n    at anonymous (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:2835:45)\n    at __guard (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:3040:15)\n    at flushedQueue (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:2834:21)\n    at invokeCallbackAndReturnFlushedQueue (http://192.168.101.4:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.reactjs.native.example.AriesBifold:2827:33)",
    "cause": {
      "name": "IndyError",
      "message": "IndySdk: Error Domain=IndyErrorDomain Code=113 \"(null)\" UserInfo={message=Error: Invalid structure\n  Caused by: Invalid bytes for \"PublicKey\"\n, indy_backtrace=}",
      "indyCode": 113,
      "indyName": "CommonInvalidStructure",
      "indyCurrentErrorJson": null
    }
  }
}
```

**Comment by standlove** [comment]
BTW, this only fails in iphone. The same works in android.

**Comment by TimoGlastra** [comment]
Has this issue been resolved @standlove?

**Comment by standlove** [comment]
Yes, we have resolved this issue.  @TimoGlastra
