### ISSUE TITLE
Indy Invalid structure error while sending presentation

### ISSUE THREAD

**Issue by afrisalyp** [hyperledger/aries-framework-javascript#545]
Hi,

I'm implementing `Share credential` with a `Presentation Proposal` as discussed here https://github.com/hyperledger/aries-framework-javascript/issues/530.

Unfortunately, I got this error in the sender side after `proposeProof` in the sender side and `acceptProposal` in the receiver side.

```
ERROR: Error handling message with type https://didcomm.org/present-proof/1.0/request-presentation {
  "message": {
    "@type": "https://didcomm.org/present-proof/1.0/request-presentation",
    "@id": "208a3469-374c-4d46-bf27-563e03c74910",
    "request_presentations~attach": [
      {
        "@id": "libindy-request-presentation-0",
        "mime-type": "application/json",
        "data": {
          "base64": "eyJuYW1lIjoicHJvb2YtcmVxdWVzdCIsInZlcnNpb24iOiIxLjAiLCJub25jZSI6InNrOWZncWIzMGpkIiwicmVxdWVzdGVkX2F0dHJpYnV0ZXMiOnsiOTRjNGFlZjktMjJhZC00NWFlLWIwMmItOTg3Y2NlZTYyNDEzIjp7Im5hbWUiOiJOYW1lIiwicmVzdHJpY3Rpb25zIjpbeyJjcmVkX2RlZl9pZCI6Ik12dTZTSjZURjZzaEFMNktuU0wyWGg6MzpDTDoyNzA4ODg6RGVmYXVsdCJ9XX0sIjM2NGZlNzhhLTJmMGYtNDkwNi1iY2I0LWQ5NTQ3ZjJmMzQ1ZCI6eyJuYW1lIjoiVHlwZSIsInJlc3RyaWN0aW9ucyI6W3siY3JlZF9kZWZfaWQiOiJNdnU2U0o2VEY2c2hBTDZLblNMMlhoOjM6Q0w6MjcwODg4OkRlZmF1bHQifV19fSwicmVxdWVzdGVkX3ByZWRpY2F0ZXMiOnt9fQ=="
        }
      }
    ],
    "~thread": {
      "thid": "77d509f8-6b4d-49c3-bdf5-409dcd9f85e8"
    }
  },
  "error": {
    "name": "IndySdkError",
    "message": "IndyError(CommonInvalidStructure): CommonInvalidStructure",
    "stack": "Error\n    at captureStackTrace (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:125013:32)\n    at BaseError (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:125055:22)\n    at construct (native)\n    at _createSuperInternal (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:124932:406)\n    at call (native)\n    at BaseError (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:124963:26)\n    at construct (native)\n    at _createSuperInternal (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:124901:406)\n    at call (native)\n    at AriesFrameworkError (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:124921:25)\n    at construct (native)\n    at _createSuperInternal (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:125796:406)\n    at call (native)\n    at IndySdkError (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:125814:25)\n    at getCredentialsForProofRequest$ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:173032:90)\n    at call (native)\n    at tryCatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:23964:23)\n    at invoke (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:24134:32)\n    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:24006:30)\n    at call (native)\n    at tryCatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:23964:23)\n    at invoke (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:24036:30)\n    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:24048:21)\n    at tryCallOne (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)\n    at anonymous (/tmp/hermes/staging/hermes/cmake/intlDebug/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)\n    at apply (native)\n    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:29333:26)\n    at _callTimer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:29229:17)\n    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:29268:17)\n    at callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:29478:44)\n    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:2996:46)\n    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:2774:45)\n    at __guard (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:2979:15)\n    at flushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:2773:21)\n    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.ariesbifold&modulesOnly=false&runModule=true:2766:33)",
    "cause": {
      "indyBacktrace": "",
      "indyCode": 113,
      "indyMessage": "Error: Invalid structure\n  Caused by: Invalid ProofRequest json has been passed\n  Caused by: Error: Invalid library state\nCaused by: Internal OpenSSL error\nCaused by: OpenSSL error\n\n",
      "indyName": "CommonInvalidStructure",
      "message": "CommonInvalidStructure",
      "name": "IndyError"
    }
  },
  "senderVerkey": "FgggNwb92ZScJhRbt66DEsSsVm8HjHc8CzBbErnkLWsK",
  "recipientVerkey": "C6AfJkVmFdLzYYhC2DQ7SnFcUss5euGsMNiXe8aoHFYy",
  "connectionId": "ce1be4fe-8b20-4be2-ab9e-a63b791072a2"
}
```

Can you please help to check if it is the correct flow? And any idea with the error message?

Thank you.

**Comment by afrisalyp** [comment]
Additional information:

When the receiver accept the presentation proposal, I pass `nonce` string in the config param.

```
agent.proofs.acceptProposal(proofRecordId, {request: {nonce: 'randomstring'}});
```

I tried without passing `nonce` string `agent.proofs.acceptProposal(proofRecordId)`, but it gave me error:

```
WalletError: Error generating nonce
```

**Comment by TimoGlastra** [comment]
I think the nonce has quite strict restrictions to it, so would recommend to let the framework generate one  for you. I have never seen this error before, and it is hard to reproduce with the context given. 

Can you share the setup you're using, which frameworks, which platform, what does the proposal look like, what are the logs. The more the better

**Comment by afrisalyp** [comment]
We are using the React Native Indy SDK wrapper https://www.npmjs.com/package/indy-sdk-react-native.
The error message `Error generating nonce` happens in both iOS and Android OS.

I just checked the wrapper code, it seems I can't find the `generateNonce` method.
Any suggestion how to implement that method?

Thank you.

**Comment by TimoGlastra** [comment]
Ah gotcha, Are both devices running on a mobile device? I personally never used AFJ as an verifier in React Native. The method was recently added to iOS: https://github.com/hyperledger/indy-sdk-react-native/pull/20

So you'd need to extend that method by adding a method in this file: https://github.com/hyperledger/indy-sdk-react-native/blob/main/android/src/main/java/com/reactlibrary/IndySdkModule.java and then updating this method to not throw an error: https://github.com/hyperledger/indy-sdk-react-native/blob/main/src/index.js#L709-L714

I think there hasn't been release yet with the iOS code, that's probably why it's not working on both platforms. If you add the method for android to indy-sdk-react-native I'll make sure to review, merge and release.

**Comment by afrisalyp** [comment]
Yes. Both are mobile devices.

Hey, I just submit a PR https://github.com/hyperledger/indy-sdk-react-native/pull/21. Kindly review.
