### ISSUE TITLE
[SOLVED] Error: libindy.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by vk1992op** [hyperledger/aries-framework-javascript#667]
Following this [walk-through](https://github.com/hyperledger/aries-framework-javascript/blob/main/docs/libindy/linux.md) led me to the error:

```
Error: libindy.so: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1168:18)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at bindings (PATHTOMYFOLDER/indy-sdk/libindy/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (PATHTOMYFOLDER/indy-sdk/libindy/node_modules/indy-sdk/src/indyBinding.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32) {
  code: 'ERR_DLOPEN_FAILED'
```

This showed up by running: 
``` 
npx -p @aries-framework/node is-indy-installed

```

EDIT: Solved by 
```
sudo /sbin/ldconfig -v
```

**Comment by TimoGlastra** [comment]
Is this on macOS or Linux?

**Comment by vk1992op** [comment]
Linux, Debian (Kali)

**Comment by TimoGlastra** [comment]
Do you have any idea what could cause this issue @blu3beri? Should we add the command (`sudo /sbin/ldconfig -v`) to the troubleshooting section?

**Comment by blu3beri** [comment]
ldconfig -v just does ldconfig in `verbose` mode. This is extremely unlikely to be the fix. Maybe reloading the shell fixed it. I've checked the guide and this error means that it could not find `Libindy.so` in the common folders (`/usr/local/lib`, `usr/lib`, etc).

**Comment by TimoGlastra** [comment]
Ok, closing this for now. Can take another look if other people have the same issue
